version: "3"

services:
  # nginx
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres

  # php
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/project
    depends_on:
      - postgres

  # postgres
  postgres:
    image: postgres:14.2-alpine
    restart: on-failure
    environment:
      POSTGRES_DB: usergroups
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATE: /var/lib/postgresql/data
    volumes:
      - ./db-data:/var/lib/postgresql/data:rw
    ports:
      - "15432:5432"
